# Generated by Django 3.0.4 on 2020-12-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlEscolar', '0003_auto_20201211_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adeudo',
            name='estado',
        ),
        migrations.AddField(
            model_name='adeudo',
            name='cargo',
            field=models.BooleanField(default=None),
        ),
    ]
