# Generated by Django 3.0.4 on 2020-12-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ControlEscolar', '0004_auto_20201211_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='historial',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='adeudo',
            name='cargo',
            field=models.BooleanField(default=None, verbose_name='Debe'),
        ),
    ]
